main/urls.py
from django.urls import path
from main.views import *

app_name = "main"

urlpatterns = [
    path('', index, name='index'),
    path('post/', Post, name='post'),
    # path('project/<int:id>/', project, name='project')

]

settins/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models


class About(models.Model):
    img = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=250)
    text = models.TextField()

    def __str__(self):
        return self.name


class What(models.Model):
    title = models.CharField(max_length=250)
    text = models.TextField()

    def __str__(self):
        return self.title


class Categoriya(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Project(models.Model):
    categoriya = models.ForeignKey(Categoriya, null=True, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='images/')





class Post(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    text = models.TextField()
    phone = models.CharField(max_length=250)

    def __str__(self):
        return self.name


# Create your models here.

main/forms.py
from django import forms
from .models import Post


class PostForms(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

main/views.py
from django.shortcuts import render, redirect
from main.models import About, Post, What, Categoriya, Project
from main.forms import PostForms
from django.contrib import messages

def index(request):
    module = Post()
    form = PostForms(request.POST, instance=module)
    print(request.POST)
    if form.is_valid():
        print("asas")
        form.save()
        messages.success(request, f"Sms malumotingiz ketdi!")
        return redirect("main:index")

    about = About.objects.all()
    what = What.objects.all()
    categoriya = Categoriya.objects.all()
    project = Project.objects.all()


    ctx = {
        "about": about,
        "what": what,
        "categoriya": categoriya,
        'project': project,
        "form": form
    }

    return render(request, 'main/index.html', ctx)


#
# def project(request, id):
#     categoriya = Categoriya.objects.all()
#     project = Project.objects.filter(categoriya_id=id)
#
#     ctx = {
#         'project': project,
#         'categoriya': categoriya
#     }
#
#     return render(request, 'main/index.html', ctx)

templates/main/kusok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="row justify-content-center">

			<div class="col-lg-8">
				<form class="contact__form form-row contact-form" method="post" action="#" id="contactForm">

					 <div class="row">
                        <div class="col-12">
                            <div class="alert alert-success contact__msg" style="display: none" role="alert">
                                Your message was sent successfully.
                            </div>
                        </div>
                    </div>

					<div class="row">
						<div class="col-lg-6">
							<div class="form-group">
								<label>ISM</label>
								<input type="text" id="id_name" name="name" class="form-control" placeholder="Ismingizni kiriting">
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>Email</label>
								<input type="text" name="email" id="id_email" class="form-control" placeholder="Email Address kiriting">
							</div>
						</div>
						<div class="col-lg-12">
							<div class="form-group">
								<label>TELEFON</label>
								<input type="text" name="text" id="id_text"  class="form-control" placeholder="Telefon raqam kiriting">
							</div>
						</div>
						<div class="col-lg-12">
							<div class="form-group">
								<label>Habar</label>
								<textarea id="id_title" name="title" cols="30" rows="8" class="form-control" placeholder="Habar malumot kiriting"></textarea>
							</div>
						</div>
					</div>
					<div class="col-lg-12">
						<div class="d-lg-flex justify-content-between mt-4">
							<p>* Rest assured.We will not spam at your inbox.</p>
							<input id="submit" name="submit" type="submit" class="btn btn-main btn-rounded" value="Post Junatish">
						</div>
					</div>
				</form>
			</div>
		</div>




</body>
</html>